- id: '1551155188930'
  alias: Heat Nursery
  trigger:
  - below: '14'
    entity_id: sensor.nursery_temperature
    platform: numeric_state
  condition: []
  action:
  action:
    service: switch.turn_on
    entity_id: switch.18480742cc50e32c3567
- id: '1551192725314'
  alias: 'Stop Heating Nursery'
  trigger:
  - above: '16'
    entity_id: sensor.nursery_temperature
    platform: numeric_state
  condition: []
  action:
    service: switch.turn_off
    entity_id: switch.18480742cc50e32c3567
~