# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Butternut Farm
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# System health
system_health:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

weather:
  - platform: environment_canada

# Sensors
sensor:
  - platform: template
    sensors:
      nextsunrise:
        friendly_name: 'Next Sunrise'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M%p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        friendly_name: 'Next Sunset'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M%p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_secret
    allowed_chat_ids:
      - !secret telegram_id

# Cloud
cloud:

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://hassio.local:9541

