- alias: Enable MQTT discovery for all devices
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/SetOption19
      payload: '1'
  id: enable_discovery
- alias: Enable mDNS for all devices
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/SetOption55
      payload: '1'
  id: enable_mdns
- alias: "Sync Tasmota states on start-up - autodiscovery"
  id: sync_tasmotas
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "tasmotas/cmnd/state"
        payload: ""
