esphome:
  name: nursery
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: '39'
  password: 'thirtyninecheminriver'

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin:
      number: 33
      mode: ANALOG
    model: DHT11
    temperature:
      name: "Nursery Temperature"
    humidity:
      name: "Nursery Humidity"
    update_interval: 60s
  - platform: adc
    name: "Plant 1 Moisture"
    # attenuation: 11db
    pin: 35
    update_interval: 5s

