esphome:
  name: nursery
  platform: ESP32
  board: nodemcu-32s
  use_custom_code: true
  includes:
    - sensors/moisture.h

wifi:
  ssid: !secret wifi_network_name
  password: !secret wifi_password


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin:
      number: 33
      mode: ANALOG
    model: DHT11
    temperature:
      name: "Nursery Temperature"
    humidity:
      name: "Nursery Humidity"
    update_interval: 60s
  - platform: custom
    id: moisture
    lambda: |-
      auto moisture_sensor = new MoistureSensor();
      App.register_component(moisture_sensor);
      return {moisture_sensor};
    sensors:
      name: "Planmmt Moisture"
      unit_of_measurement: ""
      icon: "mdi:water"
      on_value: 
        logger.log:
          format: "Plant moisture coming in at %.1f"
          args: [ 'x' ]
