esphome:
  name: nursery
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: '39'
  password: 'thirtyninecheminriver'

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin:
      number: 33
      mode: ANALOG
    model: DHT11
    temperature:
      name: "Nursery Temperature"
    humidity:
      name: "Nursery Humidity"
    update_interval: 60s
  - platform: adc
    name: "Plant 1 Moisture"
    # attenuation: 11db
    pin: 35
    update_interval: 5s

esphomeyaml:
  name: firewatch_v2
  platform: ESP8266
  board: nodemcuv2
  use_custom_code: true
  includes:
    - firewatch_v2/firewatch_sensor.h
  libraries:
    - "https://github.com/ojarva/grove-hightemp-sensor-library"

wifi:
  ssid: !secret wifi_network_name
  password: !secret wifi_password

logger:

api:

ota:

sensor:
- platform: custom
  id: thermocoupler
  lambda: |-
    auto firewatch_sensor = new FirewatchSensor();
    App.register_component(firewatch_sensor);
    return {firewatch_sensor};
  sensors:
    name: "Wood Stove Temp"
    unit_of_measurement: "°C"
    icon: "mdi:fire"
    on_value: 
      logger.log:
        format: "Stove temp is %.1f"
        args: [ 'x' ]
