esphomeyaml:
  name: weather_station
  platform: ESP8266
  board: nodemcuv2
  use_custom_code: true
  includes:
    - weather_station/weather_station.h
  libraries:
    - "Ticker"
    - "https://github.com/Bodmer/JSON_Decoder"
    - "https://github.com/Bodmer/DarkSkyWeather"
    - "https://github.com/adafruit/Adafruit-GFX-Library"
    - "https://github.com/2dom/PxMatrix.git"

#wifi:
  #ssid: !secret wifi_network_name
  #password: !secret wifi_password
  #manual_ip:
    #static_ip: 192.168.1.204
    #gateway: 192.168.1.1
    #subnet: 255.255.255.0

logger:
#   level: VERY_VERBOSE

# api:

# ota:

custom_component:
- id: weather_station
  lambda: |-
    auto weather_station = new WeatherStation();
    return {weather_station};
