esphome:
  name: workshop
  platform: ESP32
  board: nodemcu-32s
  use_custom_code: true

wifi:
  ssid: !secret wifi_network_name
  password: !secret wifi_password


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin:
      number: 33
      mode: ANALOG
    model: DHT11
    temperature:
      name: "Workshop Temperature"
    humidity:
      name: "Workshop Humidity"
    update_interval: 60s
